name: OpenIddict ATS

on: push

jobs:
  build:
    env:
      ContinuousIntegrationBuild: true
      EmbedUntrackedSources: true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1

    - name: Setup NuGet
      run: dotnet nuget add source "https://pkgs.dev.azure.com/ledgerscope/_packaging/LSFeed/nuget/v3/index.json" --name LSFeed -u ledgerscope --password ${{ secrets.LEDGERSCOPEDEVOPS }} --store-password-in-clear-text

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=4.0.${{github.run_number}}
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Package
      run: dotnet pack -p:PackageVersion=4.0.${{github.run_number}}

    - name: Publish
      run: dotnet nuget push -s LSFeed --api-key az "**/*.nupkg"

    - uses: actions/upload-artifact@v2
      if: success()
      with:
       name: Packages
       path: ./**/*.nupkg